name: SkyBlock_by_Marvin2k0
author: Marvin2k0
version: 7.5.2020
main: de.marvin2k0.skyblock.SkyBlock
commands:
  island:
    description: Island command
    permission: sky.is
    aliases: [is]
  minion:
    permission: minions.cmd
    aliases: [m]
  setlimit:
    permission: minions.admin
  blockstacker:
    permission: stacker.get
    aliases: stacker